### ISSUE TITLE
Interest in other OAuth Implementations?

### ISSUE THREAD

**Issue by DarkMio** [n4bb12/verdaccio-github-oauth-ui#101]
Hi,

we're maintaining internally a fork of this plugin to connect to Azure Active Directories via OpenID, since the process is similar (except group authentication) and I wanted to ask if there's generally interest to extend this plugin to support multiple platforms and/or more generalized OpenID logins.

If not, we're going to keep our fork separate.

**Comment by n4bb12** [comment]
I see how that would be useful but I don't have plans to extend this plugin beyond GitHub. I might write a more generic plugin in the non-near future.

**Comment by DarkMio** [comment]
I have code for that already in place. It's not even far off from this master, it mostly needs slight changes to `src/server/Config.ts` to allow for more configs (as well as the general structure of the config) and some decoupling in AuthCore. From there it's pretty smooth sailing for other providers, like Azure where the bearer token needs to access MS Graph APIs to figure out organization/group assignments.

If there's some interest, I might open up two separate PRs, one that makes configuration / API implementations more generic and after that a PR with the Azure OpenID implementation.

**Comment by OnekO** [comment]
I have a fork here which allows to login using Authelia: https://github.com/OnekO/verdaccio-github-oauth-ui

At least with Authelia it's working, I'll fix a few tests and leave there, maybe @n4bb12 wants to merge it, or maybe it will be useful to anybody who ends here looking for that.

Thx for the project, it's a good job
