### ISSUE TITLE
Installing plugin with Official Verdaccio Docker Image

### ISSUE THREAD

**Issue by macmandr197** [n4bb12/verdaccio-github-oauth-ui#119]
Is it possible to install this plugin alongside the official docker image? 
I have a Verdaccio docker image running on unraid, with a "plugin" path defined. Ideally I'd be able to download the plugin externally (not through npm), put it in the plugins folder, and somehow get them to talk to each other. I also use a proxy server, so I'd imagine I would need to put a variable called  `GLOBAL_AGENT_HTTP_PROXY` into my docker compose file in order to get things to behave properly?

**Comment by n4bb12** [comment]
There is an example Dockerfile here https://github.com/n4bb12/verdaccio-github-oauth-ui/blob/master/Dockerfile

**Comment by macmandr197** [comment]
Hmm, okay. That's what I thought. Just trying to get those commands
appended to my existing dockerfile as I have no way to modify it directly
in my environment. I have the ability to append commands on the end of the
dockerfile, but for whatever reason the USER, and RUN commands are not
recognized at all.
