### ISSUE TITLE
Can't authenticate with Enterprise github

### ISSUE THREAD

**Issue by melkosoft** [n4bb12/verdaccio-github-oauth-ui#123]
#### Versions

|                                    | Version |
| ---------------------------------- | ------- |
| node.js                            |         |
| verdaccio                          | 4.11.3    |
| verdaccio-github-oauth-ui (Plugin) |  latest   |
| verdaccio-github-oauth-ui (CLI)    |  latest  |

#### Expected behavior

I should be able to login in Verdaccio GUI after successful authentication in enterprise github.
#### Observed behaviour

Configured OAuth App in my github organization. Using clientid/secret and org name + github enterprise url configure verdaccio.
Tried to login - got redirected to my corporate auth server, successfully authenticated there and got redirected to verdaccio with error: Access denied. Log shows this error: Access denied: User "my name" is not member of "my organization name". How it can be - on my profile->organization page I am an owner!!!

**Comment by n4bb12** [comment]
Hi, maybe this is causing your issue:

> Authorize the registry to access your GitHub user and org info. You only need to do this once. If your org is private, make sure to click the Request or Grant button to get read:org access when prompted to authorize.
> https://github.com/n4bb12/verdaccio-github-oauth-ui#verdaccio-ui

**Comment by melkosoft** [comment]
I revoked all tokens in my github oauth app and tried to login again. I cleared cache and saved files. Pop up window appeared asking to authorize read access - I authorised, went though login process and got Access denied again - user XXX is not member of organization YYYY

**Comment by melkosoft** [comment]
I found one more thing - api.{github enterprize url} is not in Subject Alt Names of certificate - may it be the reason for application to file?
