### ISSUE TITLE
htpasswd users can't login via npm if github-oauth-ui is active

### ISSUE THREAD

**Issue by hybridherbst** [n4bb12/verdaccio-github-oauth-ui#140]
## Bug Report

Verdaccio auth plugins usually fall back gracefully in the order of declaration, however, it seems that github-oauth-ui blocks access to htpasswd (the default auth plugin).

#### Expected behavior
When logging in via npm with a user:password combination that is registered in the htpasswd file, user can log in.

#### Observed behaviour
Some logs appear that github-oauth-ui tries to add the user, which fails since it exists, and the user can't log in.

#### Steps to reproduce

1. Make sure htpasswd auth and github-oauth-ui are both on
2. Try to log in via npm login with a user:password combination as set in htpasswd
3. Note the logs on the server that the user can't be created and hasn't successfully logged in

**Comment by n4bb12** [comment]
I looked into it and verified that both authentication methods (this plugin + htpasswd) can be used together. I think the plugin already does this correctly. This has been looked at and fixed here: https://github.com/n4bb12/verdaccio-github-oauth-ui/issues/17. 

Please make sure you are using the plugin as described in the README including the hints in troubleshooting section.

After checking the README if you still think there is an issue, please share your configuration and Verdaccio logs.

**Comment by n4bb12** [comment]
You can see this correctly implemented [here](https://github.com/n4bb12/verdaccio-github-oauth-ui/blob/ea7555814e8f0aa7f64776825c4d30b819af0115/src/server/plugin/Plugin.ts#L67) and the relevant docs [here](https://verdaccio.org/docs/plugin-auth/#if-the-authentication-fails).
