### ISSUE TITLE
Need help creating the_authToken "SECRET_TOKEN"

### ISSUE THREAD

**Issue by mopinon** [n4bb12/verdaccio-github-oauth-ui#141]
Hi, I am making my wrapper to integrate Verdaccio with Unity based on your plugin.
I have a problem with creating a _authToken.
As I understand the algorithm of actions:
1) Request a user's GitHub identity `https://github.com/login/oauth/authorize?client_id={value}&scope=read%23org,repo`
2) Getting code from github `{my-host-ip}/-/oauth/callback?code={code-from-github}`
3) Create string `{username}:{code-from-github}`
4) AES encrypt this string (What is the key?)
5) Convert to Base64 string. (Will the result be an _authToken?)

Thanks in advance for your help!
Thanks for the plugin!

**Comment by n4bb12** [comment]
Hi

I'm not sure what you are trying to do here.

Are you using this plugin?
Then there should not be any need to implement the above steps.

Are you looking for advice on how to implement a plugin of your own?
Then I'd recommend checking the Verdaccio docs.
