### ISSUE TITLE
Allow disabling repository authentication

### ISSUE THREAD

**Issue by thatsmydoing** [n4bb12/verdaccio-github-oauth-ui#144]
https://github.com/n4bb12/verdaccio-github-oauth-ui/issues/136 adds restricting via repository but also adds the requirement of private repository access when logging in. We don't use this feature and would rather limit the scopes as much as possible.

**Comment by Ran-QUAN** [comment]
My organization can't issue access tokens with `repo` scope, an option to disable this requirement would be nice.

**Comment by n4bb12** [comment]
Hi @thatsmydoing, I don't understand. Could you explain in more detail, please?

**Comment by thatsmydoing** [comment]
Prior to #136, when a user logs in the Github OAuth screen only asks for reading organization permissions. After #136, when a user logs in again, the Github OAuth screen shows up asking to approve reading repository permissions. In our case, we don't use the feature to restrict access by repository and would rather not expose (possibly private) repository information to verdaccio.

**Comment by n4bb12** [comment]
Okay got it. Thanks for explaining and submitting a PR 🙏
