### ISSUE TITLE
Help text is not replaced in verdaccio 5.5.x and up

### ISSUE THREAD

**Issue by thatsmydoing** [n4bb12/verdaccio-github-oauth-ui#151]
## Bug Report

The registry info dialog no longer displays the instructions to add the authToken in verdaccio 5.5 and up. It seems the UI has changed slightly that the selector does not match any more.

### Versions

|             | Version |
| ----------- | ------- |
| Verdaccio   |  5.5.1       |
| This plugin | 3.2.0        |
| Node.js     |  14.18.1       |

### Observed behavior

The registry info dialog displays instructions for

```
npm set registry https://registry.example.com/
npm adduser --registry https://registry.example.com/
npm profile set password --registry https://registry.example.com/
```

### Expected behavior

It should contain
```
npm config set //registry.example.com:_authToken myauthtoken
npm config set //registry.example.com:always-auth true
```

**Comment by n4bb12** [comment]
Thank you for reporting 🙏

**Comment by NudeNULL** [comment]
Yes please fix this because I have access to one package as an admin and can't see the token so I can set it on my machine in powershell
