### ISSUE TITLE
Cannot copy the commands from the Web UI to use in command line

### ISSUE THREAD

**Issue by NudeNULL** [n4bb12/verdaccio-github-oauth-ui#152]
### Versions

|             | Version |
| ----------- | ------- |
| Verdaccio   |     5.6.0    |
| This plugin |    3.2.4     |
| Node.js     |    16.14.0     |

### Environment

|                  | Name | Version |
| ---------------- | ---- | ------- |
| Package manager  |   npm   |    8.5.1     |
| Browser          |   Chrome   |    Version 98.0.4758.102 (Official Build) (64-bit)     |
| Operating system |   Windows 10   |   Version	10.0.19042 Build 19042     |

### Observed behavior

When I try to copy the command line commands, it doesn't do anything, so I can find the full token only if I inspect the page. Also it throws some errors
![image](https://user-images.githubusercontent.com/15786742/154978076-1c6cc7f9-9885-4d90-97b1-f2c0a94b163f.png)

### Expected behavior

It should copy the commands

### Steps to reproduce

1. Try to copy the commands
2. Paste somewhere to find out it was not copied

**Comment by n4bb12** [comment]
Thanks for reporting.
Could this be your problem? https://github.com/n4bb12/verdaccio-github-oauth-ui/issues/145#issuecomment-1029874612

**Comment by NudeNULL** [comment]
@n4bb12, yeah it is, thanks!
