### ISSUE TITLE
I need help to debug this plugin

### ISSUE THREAD

**Issue by lankerxd** [n4bb12/verdaccio-github-oauth-ui#154]
As shown in title , I know how to debug  verdaccio source code . 
 I tried to introduce it in verdaccio , and Modify main in package.json is
"src/server/index.ts". but it didn't succeed. so can give me some advice ? thanks.

**Comment by n4bb12** [comment]
Hi @lankerxd 

I'm not sure what you're trying to do. Could you share some more context, please?

**Comment by lankerxd** [comment]
> Hi @lankerxd
> 
> I'm not sure what you're trying to do. Could you share some more context, please?



> Hi @lankerxd
> 
> I'm not sure what you're trying to do. Could you share some more context, please?

I try to debug verdaccio-github-oauth-ui 。I try to introduce it into verdaccio source code to debug , but it didn't succeed 。Can you tell me how you did it。

**Comment by lankerxd** [comment]
> Hi @lankerxd
> 
> I'm not sure what you're trying to do. Could you share some more context, please?

Hi @[n4bb12](https://github.com/n4bb12) I try to debug verdaccio-github-oauth-ui 。I try to introduce it into verdaccio source code to debug , but it didn't succeed 。Can you tell me how you did it。

**Comment by n4bb12** [comment]
Could you describe what you mean by "debug"?

**Comment by lankerxd** [comment]
> Could you describe what you mean by "debug"?

It's debugging ， see this link : https://github.com/verdaccio/verdaccio/wiki/Debugging-Verdaccio 。
I create a debug configuration in VSCODE .
![image](https://user-images.githubusercontent.com/43224933/159011650-225efe83-e6a5-4ea5-a89a-ec4972982d57.png)

**Comment by n4bb12** [comment]
Don't try to debug the plugin directly. It doesn't run standalone, it only works as a Verdaccio plugin.
If you install the plugin as usual and debug Verdaccio, you can automatically debug the plugin, too.

**Comment by lankerxd** [comment]
I know the plugin is part of verdaccio 。I try to debug plugin source code，When verdaccio loading plugin ,it failed to load successfully。
I changed the configuration of the file : package.json
![image](https://user-images.githubusercontent.com/43224933/159014593-6decc1b9-f72a-4599-8556-3b4ff8537bf5.png)
This is the error of loading failure:
![image](https://user-images.githubusercontent.com/43224933/159015160-7cae361e-6949-472c-b2fe-8e17babfb845.png)

**Comment by lankerxd** [comment]
[](https://user-images.githubusercontent.com/43224933/159014593-6decc1b9-f72a-4599-8556-3b4ff8537bf5.png)I know the plugin is part of verdaccio 。I try to debug plugin source code，When verdaccio loading plugin ,it failed to load successfully。
I changed the configuration of the file : package.json
![image](https://user-images.githubusercontent.com/43224933/159015305-87064780-5a56-46d0-828e-29525fa4fd0c.png)

**Comment by n4bb12** [comment]
Modifying the `package.json` won't help you. `index.ts` is TypeScript and can't be run by node like that.

If you want to start Verdaccio with the plugin from within this repository I would recommend running `yarn dev`.

**Comment by lankerxd** [comment]
well,
I seem to understand ,thanks much.

**Comment by lankerxd** [comment]
I've made some attempts these days, but I doesn't succeed. I want to know is  how to debugging when start Verdaccio with the plugin from within this repository .
Looking at the following picture, I can debug the code in the dist folder, but because after parcel build, the method name is renamed and all the contents are placed in one JS file, it is more difficult to debug.
![image](https://user-images.githubusercontent.com/43224933/159197911-520002c8-33fc-4838-a0d6-eb0dfb32e973.png)

**Comment by lankerxd** [comment]
I solved the problem by using TSC to build the server folder and vite (Iife) to build the client folder. Although there are still some problems in the build of the client folder,But it's ready for debugging.
![image](https://user-images.githubusercontent.com/43224933/160510610-a3d86893-fa82-4f87-ad7a-9ca9b3c8eb7f.png)
