### ISSUE TITLE
Running `npm run dev` doesn't seem to properly set up local development

### ISSUE THREAD

**Issue by hybridherbst** [n4bb12/verdaccio-github-oauth-ui#156]
## Bug Report

I was trying to run `npm run dev` locally to test changes to the plugin. 
However, it seems that doesn't work anymore- seems the plugin is loaded (I can see that in the terminal), but the actual deployment file isn't found and thus while Verdaccio works, the OAuth UI doesn't:
![image](https://user-images.githubusercontent.com/2693840/167624824-22231c2e-317c-4e36-aa84-ad316914394f.png)

Terminal output looks ok:
![image](https://user-images.githubusercontent.com/2693840/167625210-eca9e48b-b6e1-4a1e-a7e2-ce855f010cd0.png)

So I can only assume that some of the copy steps aren't correct anymore maybe?
Are there additional steps for local development?

### Suggested implementation
Would be great if there are steps listed in the Readme for setting up local development.

**Comment by n4bb12** [comment]
Might be related to npm. I did `git pull && yarn && yarn dev` and got this.

![2022-05-10 19_25_53-Verdaccio](https://user-images.githubusercontent.com/6810177/167687201-5c495d59-34ac-4372-a460-f839fe91f231.png)

If you're using npm there is no lockfile, so you might end up with an incompatible set of dependencies, potentially a new verdaccio version with breaking changes.

**Comment by hybridherbst** [comment]
According to package.json `npm run dev` simply calls `yarn && yarn dev`. I tried it nonetheless but get the same behaviour.
I'll try to start "from scratch" but not sure what exactly could have gone wrong, this was a fresh clone anyways. I'll keep you posted!

**Comment by n4bb12** [comment]
Feel free to post a PR or comment if you come across a solution or find out more about what might be causing this.

**Comment by n4bb12** [comment]
I ran a dependency update as part of project maintenance and then ran into the same issue. So I'm infering that you didn't use yarn and hence the yarn lock file to install dependencies, but did it with npm which would ignore the yarn.lock.

Please try deleting `node_modules` and then run `yarn && yarn dev` exactly like that.
