### ISSUE TITLE
Simplify access requests with `repo:status` instead of `repo`

### ISSUE THREAD

**Issue by hybridherbst** [n4bb12/verdaccio-github-oauth-ui#157]
### Description

Currently, using github-oauth-ui requires a very high level of permissions for granular repo access, namely the `repo` scope:
> Grants full access to repositories, including private repositories. That includes read/write access to code, commit statuses, repository and organization projects, invitations, collaborators, adding team memberships, deployment statuses, and repository webhooks for repositories and organizations. Also grants ability to manage user projects.

This is scary, and rightfully so! It shows a big warning when people click on "Login" that whoever requested the login will gain very permissive access rights that are actually not needed.

I believe it was necessary at the time of implementation because this was the only scope available for repos, but by now there's (I believe) a new one that might be sufficient - `repo:status`:

> Grants read/write access to commit statuses in public and private repositories. This scope is only necessary to grant other users or services access to private repository commit statuses without granting access to the code.

### Suggested implementation

Use `repo:status` instead of `repo` oauth scope

### Possible alternatives

Alternative thing to try could be `repo_deployment`.

**Comment by n4bb12** [comment]
It's broad, yes, but if we're talking private repositories, that's the only scope available. `repo:status` refers to public repositories.

The token is shared with your Verdaccio instance and stored on the signed-in person's machine (browser and/or npm config). Both verdaccio and this plugin are open source. You have full control over what else you install on your instance.

If you still find that scary, I'm afraid I can only recommend using a different authorization mechanism.

**Comment by n4bb12** [comment]
Of course, I'm open if you have any more ideas on how to reduce the requested scope.

**Comment by hybridherbst** [comment]
The description of `repo:status` mentions both public and private repositories.

Just to clarify: it isn't scary when used inside an organization - it's scary for other people. Our usecase is giving other people access to packages based on which GitHub repos they have read and issue access to.

**Comment by n4bb12** [comment]
Maybe I'm misunderstanding how `repo:status` works. I'll try it out and see if I can make it work.

**Comment by n4bb12** [comment]
I tried `repo:status` and `repo_deployment` but neither of them grant visibility to private repositories.

The way I understand the docs, they only grant visibility to commit and deployment statuses, respectively, but not to the repository itself. Hence it's not included if you fetch a list of repositories.

**Comment by n4bb12** [comment]
Maybe we could offer using an owner token as an opt-in config option. So instead of using the signed-in user token and check `user-->repositories`, we could use a token created by the org/repo owner and check `repository-->users`. That way we would not need to request anything from the registry users at all.

**Comment by n4bb12** [comment]
It's just an idea, I'm not sure if it would work in combination with how Verdaccio relies on groups, but maybe we can make it work somehow.

**Comment by hybridherbst** [comment]
Do you happent to know if this would work if the users are external collaborators and not team members? Sounds interesting – and I wouldn't mind extra configuration steps

**Comment by n4bb12** [comment]
I would assume it does because the repo owner (and hence the configured token) can see and change who is a collaborator.

**Comment by n4bb12** [comment]
Implemented in https://github.com/n4bb12/verdaccio-github-oauth-ui/releases/tag/5.0.0.
Note that this is a major release that introduces some breaking changes.
