### ISSUE TITLE
Installing with npm fails

### ISSUE THREAD

**Issue by philicious** [n4bb12/verdaccio-github-oauth-ui#16]
## Bug Report
When installing this plugin with `npm` according to the README, it doesnt work due to dependency problems.
The explanation is quite simple: verdaccio itself uses yarn and a `yarn.lock` file in contrary to a `package-lock.json` , so adding new dependencies such as this plugin, needs to be done with `yarn add verdaccio-github-oauth-ui`

#### Versions

|                           | Version |
| ------------------------- | ------- |
| verdaccio                 |   3.11.6      |
| verdaccio-github-oauth-ui |    latest     |

#### Expected behavior
following README will work

#### Observed behaviour
installation according to README fails

**Comment by n4bb12** [comment]
Thanks for taking time to make a report.

The npm example is just there to make the package name more visible. I would rather keep it simple and not add an example for each package manager. If you know how to use yarn, it should be trivial to adapt the command for yarn.
