### ISSUE TITLE
always-auth no longer available

### ISSUE THREAD

**Issue by dataviruset** [n4bb12/verdaccio-github-oauth-ui#170]
### Versions

|  Software   | Version |
| ----------- | ------- |
| This plugin |   v5.0.3   |
| Node        |   v19.4.0  |
| NPM       | 9.2.0 |

### Environment

| Type | Name | Version |
| ---------------- | ---- | ------- |
| Package manager  |  Homebrew    | 3.6.18    |
| Browser          |  Firefox  | 108.0.2  |
| Operating system |  macOS  | Ventura 13.1  |

### Observed behavior

After running `npx verdaccio-github-oauth-ui`, in the browser window that opens, it cannot write to the `.npmrc` file because of this error:
```
Command failed: npm config set //npm.redacted.com/:always-auth true npm ERR! `always-auth` is not a valid npm option npm ERR! A complete log of this run can be found in: npm ERR! /Users/oskar/.npm/_logs/2023-01-16T14_56_06_386Z-debug-0.log 
```

It seems `always-auth` has been obsolete from NPM v7 and forward, at least in the documentation. Here's a link to the [documentation](https://docs.npmjs.com/cli/v6/using-npm/config?v=true#always-auth) for v6. However, I tried with NPM v8 and it still works, so likely it has been removed in v9.

### Expected behavior
That the authentication would succeed without error messages.

Maybe `always-auth` needs to be disabled if `verdaccio-github-oauth-ui` is running with a later NPM version, or if there's a replacement, couldn't find anything though, so it might have just been removed.

**Comment by n4bb12** [comment]
Thanks for bringing this up. I think we can safely remove this option then. I'll do a major release to mark it as a breaking change in case someone is using npm 6 or older.

**Comment by n4bb12** [comment]
🔗 https://registry.npmjs.org/package/verdaccio-github-oauth-ui
🔗 https://github.com/n4bb12/verdaccio-github-oauth-ui/releases/tag/6.0.0
