### ISSUE TITLE
Access allowed for revoked GitHub tokens

### ISSUE THREAD

**Issue by philicious** [n4bb12/verdaccio-github-oauth-ui#19]
#### Versions

|                           | Version |
| ------------------------- | ------- |
| verdaccio                 |   3.11.6      |
| verdaccio-github-oauth-ui |     1.7.2    |

#### Expected behavior
- When removing a user from GitHub organization ..
- When revoking all user tokens in the GitHub OAuth application..
.. user shouldnt be able anymore to pull packages

#### Observed behaviour
User is still able to `npm install` packages with the old token.

You have to restart verdaccio and then the user is blocked.

#### Additional context
Verdaccio is installed on kubernetes with Helm Chart.

I was reading the plugin code and had the impression the tokens are saved nowhere besides browser LocalStorage aswell as cached for 30s but then re-validated against GitHub.

I cannot explain to myself how verdaccio still accepts the invalid tokens?

**Comment by n4bb12** [comment]
Restarting Verdaccio should not change anything. Have you tried this multiple times? Do you think it is possible that GitHub just needed a while to invalidate the token/delete the user, and restarting Verdaccio was just pure coincidence?

**Comment by philicious** [comment]
sorry for delay:
yes, at least me and a co-worker individually noticed it initially and then did tests with a new and dedicated test-user in Github with the results as described above.

Restarting verdaccio successfully and immediately ensures the invalid tokens are actually not granted any access anymore. If you do not restart, access is still granted.

**Comment by n4bb12** [comment]
Thanks for the info. I will look into it.

**Comment by n4bb12** [comment]
The expires comparison is oncorrect. It should be `details.expires < Date.now()`
https://github.com/n4bb12/verdaccio-github-oauth-ui/blob/master/src/server/plugin/Plugin.ts#L80

**Comment by n4bb12** [comment]
Fixed in [1.10.1](https://github.com/n4bb12/verdaccio-github-oauth-ui/releases/tag/1.10.1)

**Comment by philicious** [comment]
oh dear, haha .. such things happen. thanks for fixing @n4bb12 !
