### ISSUE TITLE
Loading verdaccio-5.js is not taking the url_prefix into consideration

### ISSUE THREAD

**Issue by codewing** [n4bb12/verdaccio-github-oauth-ui#195]
### Versions

|             | Version |
| ----------- | ------- |
| Verdaccio   |    5.31.0     |
| This plugin |   6.0.4   |

### Environment

docker verdaccio container hosted at `example.com` with `url_prefix: /npm/`

### Observed behavior

Loading failed for the <script> with source “https://example.com/-/static/github-oauth-ui/verdaccio-5.js”.

### Expected behavior

I expected the plugin to serve the JS file at https://example.com/npm/-/static/github-oauth-ui/verdaccio-5.js
(Note the npm after example.com)

### Steps to reproduce

setup a server with a url_prefix

### Additional context

I think this line here should take the url_prefix into consideration: https://github.com/n4bb12/verdaccio-github-oauth-ui/blob/d3b50a228a26ee5fe3cad0a725b60b9d8afb15f6/src/server/plugin/PatchHtml.ts#L10

**Comment by n4bb12** [comment]
Thanks for the report. The plugin now takes the `url_prefix` into account using `getPublicUrl` from `@verdaccio/url`.
