### ISSUE TITLE
Auth Token from npx verdaccio-github-oauth-ui expiration

### ISSUE THREAD

**Issue by blasco** [n4bb12/verdaccio-github-oauth-ui#199]
Is there away to control the expiration time of the generated token? Or how should the token be generated to prevent its expiration? I'm using this token to publish packages in a github action, but it seems that the token expires after a couple of days. I generate it via:

```
npx verdaccio-github-oauth-ui --registry
```

I can't find in the documentation how to identify in a CI setup. Is there a recommended approach?

**Comment by n4bb12** [comment]
Token formats and durations are goverened by Verdaccio. Take a look at
- https://github.com/verdaccio/verdaccio/issues/1231
- https://verdaccio.org/docs/configuration#security

**Comment by blasco** [comment]
According to the documentation the tokens do not expire. I'm deploying verdaccion in google cloud run, so my guess is that when the container is shut down, the logged in user tokens are lost... Is there a way to log in via cli? currently I'm ussing npx verdaccio-github-oauth-ui --registry, but that opens the web  browser to log in, is there another method to log in that could be performed in a ci environment? Thank yo!

**Comment by n4bb12** [comment]
> According to the documentation the tokens do not expire.

?

<img width="689" alt="2024-06-04 13_53_39-Configuration File _ Verdaccio" src="https://github.com/n4bb12/verdaccio-github-oauth-ui/assets/6810177/098c0ea8-2e13-4ff6-9118-7da6fe019b3f">

> is there another method to log in that could be performed in a ci environment

This plugin performs an OAuth Authorization Code Flow which is inherently interactive and browser-based, and requires redirecting through GitHub. That is the whole and sole purpose of this plugin. If you want a non-interactive way of signing in, best use a different plugin.

**Comment by blasco** [comment]
As far as I understood, the jwt is not the default behaviour, the default one does not use jwt and do not expire. Maybe I'm missing something
