### ISSUE TITLE
Access denied: user X is not a member of Y

### ISSUE THREAD

**Issue by vshia** [n4bb12/verdaccio-github-oauth-ui#34]
#### Versions

|                           | Version |
| ------------------------- | ------- |
| verdaccio                 |  	4.3.4       |
| verdaccio-github-oauth-ui |   2.0.1     |

#### Expected behavior
Logging in with the CLI via the instructions [here](https://github.com/n4bb12/verdaccio-github-oauth-ui#command-line) and running `npm whoami --registry http://localhost:4873` should show the user's github username.

#### Observed behaviour
I get an auth token error.
```
npm ERR! code ENEEDAUTH
npm ERR! need auth Your auth token is no longer valid. Please log in again.
npm ERR! need auth You need to authorize this machine using `npm adduser`
```
As a result, I can't run `npm publish`

#### Steps to reproduce
Follow the instructions in https://github.com/n4bb12/verdaccio-github-oauth-ui#command-line to setup the config.yaml file.
To confirm that it at least works nominally, I can log on via the Web UI. When logging in on the web, I see the Github Oauth page and after accepting it, I get to the normal Verdaccio page.

#### Additional context

My `~/.npmrc` file (to confirm that the instructions ran correctly):
```
registry=http://localhost:4873/
//localhost:4873/:_authToken=[AUTH_TOKEN]
//localhost:4873/:always-auth=true
```

Not sure if this is relevant but on the terminal logs, after I log in on the web, I see the following:
```
...
verdaccio    | github-oauth-ui Access denied: user "vshia" is not a member of "[ORG]"
verdaccio    |  http <-- 304, user: vshia(172.28.0.1), req: 'GET /-/verdaccio/packages', bytes: 0/0
verdaccio    | github-oauth-ui Access denied: user "vshia" is not a member of "[ORG]"
verdaccio    |  http <-- 304, user: vshia(172.28.0.1), req: 'GET /-/verdaccio/packages', bytes: 0/0
verdaccio    |  http <-- 304, user: null(172.28.0.1), req: 'GET /-/static/b1e0d4d4ee23474aee6616f444fc7aa9.svg', bytes: 0/0
...
```
which is strange b/c the web UI seems to successfully login and show that I'm logged in.

Did I miss something? or is this a new issue with Verdaccio 4?

**Comment by n4bb12** [comment]
Thanks for reporting.

Is it possible that you're using a token that was generated by verdaccio 3 and the you copied it from the v4 UI?

Have you tried logging out and back in and using the new token?

**Comment by humandx-team** [comment]
Ah, I got this working. I think the problem was that I was using a different config file (my docker-compose.yaml file mapped `./config` to `/verdaccio/conf`. When I pointed it to my custom config file, things started to work. Sorry for the trouble.

**Comment by vshia** [comment]
Ah, I got this working. I think the problem was that I was using a different config file (my docker-compose.yaml file mapped ./config to /verdaccio/conf. When I pointed it to my custom config file, things started to work. Thanks and sorry for the trouble.
