### ISSUE TITLE
Missing lodash dependency

### ISSUE THREAD

**Issue by ir-fuel** [n4bb12/verdaccio-github-oauth-ui#42]
#### Versions

|                           | Version |
| ------------------------- | ------- |
| verdaccio                 |  4.4.2       |
| verdaccio-github-oauth-ui | 2.2.2         |

#### Expected behavior
The plugin should load when starting Verdaccio.

#### Observed behaviour
The loader bails out because `Cannot find module 'lodash'`

#### Additional context
lodash is declared as a peer dependency, however on my Verdaccio install, when trying to load the plugin, it gives me an error on lodash. Doing `npm install lodash` inside your plugin's directory solves the issue.

It's related to this issue where it all started:
https://github.com/verdaccio/verdaccio/issues/1677#issuecomment-575833500

**Comment by n4bb12** [comment]
Thanks for reporting, I'll look into this.

**Comment by n4bb12** [comment]
The plugin is not found because you're installing it globally. This is something npm doesn't support. Lodash is unrelated to this problem. I've commented on the Verdaccio issue.
