### ISSUE TITLE
NPM commands failing

### ISSUE THREAD

**Issue by thomasdavis** [n4bb12/verdaccio-github-oauth-ui#5]
After setting up the plugin successfully, I manage to oauth in and see packages listed by basic auth users.

I copy the commands shown and my `.npmrc` file looks like this 

```
//npm.mycompani.io/:_authToken="i/sKvYrKJKXupSfYB5dtYTI6un65wGg4f/rBF8YanVrTw8NjUzT5GPTJNbDa0NJCnVmIWQIXMfSsV5og1+QrYw=="
//npm.mycompani.io/:always-auth=true
```

Though when I try to `publish` or `whoami` with the `--registry xxx` flag I get 

```
Your auth token is no longer valid. Please log in again.
``` 

This is moments after creating it. From my understanding, Verdaccio should be persisting the npm token somewhere so that it can match it later. (like how .htpasswd plugin works)

But after looking around in my Verdaccio instance, I can see no mention of my token or my github username.

p.s. cool plugin =D

**Comment by psyhomb** [comment]
I'm experiencing exactly the same issue 

```
# npm whoami --registry xxx
npm ERR! code ENEEDAUTH
npm ERR! need auth Your auth token is no longer valid. Please log in again.
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-30T14_21_36_340Z-debug.log
```

**Comment by abrsil-WittGruppe** [comment]
Is this part set in your verdaccion config?
```
auth:
  github-oauth-ui:
    org: $GITHUB_OAUTH_ORG # required, people within this org will be able to auth
```

Are you using a private org?
If yes then my guess is that you might have not requested the `org:read` permission.

When initially logging in and authorizing the GitHub app, there's a convenient little `[Request]` button that is can be easily overlooked. It is important that you klick it.

An org admin will then need to grant this permission.

When logging in, the plugin uses your token to fetch the orgs you are in. Without this permission, the org will not be listed, and it will seem as if you are not part of the org.

**Comment by psyhomb** [comment]
🤦‍♂️  You are completely right, that's the reason! Thanks mate!

**Comment by thomasdavis** [comment]
@abrsil-WittGruppe Thanks for the quick reply.

We just found out what our problem was -.- The organisation we were working with had a capital as the first letter and we were entering all lower case. Pretty frustrating =D But we are happy campers now, thanks again.
