### ISSUE TITLE
Cannot GET / in the UI

### ISSUE THREAD

**Issue by ganapativs** [n4bb12/verdaccio-github-oauth-ui#57]
## Bug Report
Plugin breaks with `Cannot GET /` in the UI when running with `npx verdaccio-github-oauth-ui@2.3.1 --registry https://registry.website.com/`. This started happening from `2.3.1`. The plugin works fine till `2.3.0`. 

<img width="738" alt="Screenshot 2020-08-12 at 9 49 53 AM" src="https://user-images.githubusercontent.com/4010960/89974626-349fc800-dc81-11ea-9df4-529111733719.png">

Tested on Mac and Ubuntu, facing the same issue.

#### Versions

|                           | Version |
| ------------------------- | ------- |
| verdaccio                 | 4.7.1   |
| verdaccio-github-oauth-ui | 2.3.1   |

#### Expected behavior

Should successfully authenticate and update the `.npmrc` file.

#### Observed behaviour

Plugin breaks with `Cannot GET /` in the UI

#### Steps to reproduce

1. Run `npx verdaccio-github-oauth-ui@2.3.1 --registry https://registry.website.com/`
2. Plugin breaks with `Cannot GET /` in the UI

**Comment by n4bb12** [comment]
Do you have the same problem with `2.3.2`?

**Comment by ganapativs** [comment]
Yes. Both `2.3.1` and `2.3.2` has the same issue. For now, I'm sticking with `2.3.0`.

**Comment by ganapativs** [comment]
Also, the command is still waiting even after the error occurs.

<img width="682" alt="Screenshot 2020-08-12 at 4 36 39 PM" src="https://user-images.githubusercontent.com/4010960/90008476-07bbd700-dcba-11ea-9533-622b4dc4f24d.png">

**Comment by ganapativs** [comment]
Also, the command is still waiting even after the error occurs.

<img width="680" alt="Screenshot 2020-08-12 at 4 39 42 PM" src="https://user-images.githubusercontent.com/4010960/90009042-f7582c00-dcba-11ea-9eb5-39ba2c75eb74.png">

**Comment by n4bb12** [comment]
Found the issue. It took me a while to reproduce because it requires a different server and CLI version.

In 2.3.0 the CLI callback path is `/`.
In 2.3.1 the CLI callback path changed to /success, /denied and /error. But while the CLI handles redirection and writing the token to `.npmrc`, the corresponding callback request handler is registered by the server-side Verdaccio plugin. This is an unclean mix of concerns.

**Comment by ganapativs** [comment]
Yes, there is a version mismatch. on the client-side, I was trying with `2.3.1`, while, the server has `2.2.4`. 

On a side note: should we ask for both client and server versions in issue template?

**Comment by n4bb12** [comment]
good idea, we could add the node version, too

**Comment by n4bb12** [comment]
CLI [2.3.3](https://github.com/n4bb12/verdaccio-github-oauth-ui/releases/tag/2.3.3) works with server versions `<=2.3.0` and `>=2.3.3`.

Thanks you for reporting it!
